#!/bin/bash
MESSAGE=`git log -1 HEAD --pretty=format:%s`
HASH=`git log -1 HEAD --pretty=format:%H`
USEREMAIL=`git log -1 HEAD --pretty=format:%ce`
DATE=`git log -1 HEAD --pretty=format:%cd`
GITLOGFILES=`git diff-tree --no-commit-id --name-only -r $HASH | tr '\n' ','`

if [[ $MESSAGE == *"#gamify"* ]]; then
	echo `date --rfc-3339=seconds` - Received commit \n >> /git/logs/qualygame.log
	echo `node /home/qualygame/qualygame/Client-cli/client-cli.js $HASH "$MESSAGE" $USEREMAIL "$DATE" $GITLOGFILES` >> /git/logs/qualygame.log
else
	echo "Sem Tag" >> testeTag.txt
fi
